### ISSUE TITLE
How to implement repeterVal ()

### ISSUE THREAD

**Issue by jorarmarfin** [DubFriend/jquery.repeater#45]

**Comment by jorarmarfin** [comment]
please

**Comment by yociduo** [comment]
please use $repeater.repeaterVal()

**Comment by jorarmarfin** [comment]
How to use it

**Comment by yociduo** [comment]
$repeater is your element.
For the title, I guess you have miss spelling with the extension name.

**Comment by jorarmarfin** [comment]
I just wrote it well but I do not know how to use that command, as I
captured the variables of each repeated input

**Comment by yociduo** [comment]
There is an example in the README.md, you can try it.
It will return an object for form

**Comment by jorarmarfin** [comment]
In the README.md file only mentions
// setup the repeater
$ ('. Repeater').
// get the values of the inputs as a formatted object
$ ('. Repeater').
But I still do not know how to use repeaterVal ()
An example please

**Comment by DubFriend** [comment]
the `repeaterVal` method is sort of convenience method to get the values of inputs within the repeater.

The original design of jquery.repeater was to be used in a "web 1.0" style, where the form triggers a full page refresh (as opposed to an ajax call). jquery.repeater sets the `name` parameter in a way that it generates a nicely structured data when parsed on the server (at least in php). For example an input in jquery.repeater with the name "foo" would be rewritten to something like "repeater-name[0][foo]" so that it is parsed on the server as an element in an array with the field name "foo". In this case you probably wouldn't need to use `repeaterVal`. 

However if you need to access the values of repeater inputs using client side javascript, this naming convention could be annoying. So `.repeaterVal` returns the data in a structured way that would mirror the way your server-side parsing might structure it.

Your best bet might be to simply try calling `repeaterVal` on a repeater and see what data it returns. This would probably be more instructive than my poor explanation 😄
