### ISSUE TITLE
Issue with radio inputs

### ISSUE THREAD

**Issue by camiloclc** [DubFriend/jquery.repeater#8]
It seems that when I click the data-repeater-create button, the data-repeater-item that was cloned (the first one) has it's checked attribute cleared. Happens with latest Firefox and Chrome.

**Comment by DubFriend** [comment]
The intended behavior is to clear the input values of the first data-repeater-item when it is used for creating new items.

You can set default values of newly created items like this.

```javascript
$('.repeater').repeater({
    defaultValues: {
        'textarea-input': 'foo',
        'text-input': 'bar',
        'select-input': 'B',
        'checkbox-input': ['A', 'B'],
        'radio-input': 'B'
    }
});
```

Please let me know if this solves the problem.

Thanks :smiley:

**Comment by camiloclc** [comment]
It's not a problem with default values, I need the user to either choose Yes or No. When the data-repeater-item template is empty (inputs unchecked by default), there's no problem - if I check one of the radio inputs and click the data-repeater-create button to create another item, the radio value is preserved. On the other hand, if the template (first data-repeater-item) has already been populated, the radio input gets unchecked every time I click on the data-repeater-create button.
Thanks for the help!

**Comment by DubFriend** [comment]
I see, that definitely sounds like a bug.  I will look into this.

Thanks!

**Comment by DubFriend** [comment]
Hey sorry for the late reply I have been swamped at work lately.

I am unable to reproduce this. Could you provide a simplified code sample that reproduces the issue?

**Comment by camiloclc** [comment]
Hey Brian, please give me a few days, I'm also swamped!

**Comment by cawecoy** [comment]
@camiloclc @DubFriend I just had the same issue and finally got to solve it.

In my edit form I rendered inputs' name already with the group and index:

```
    <div data-repeater-list="group-a">
      <div data-repeater-item>
        <input type="radio" name="group-a[0][radio-input]" value="A" checked/>
        <input type="radio" name="group-a[0][radio-input]" value="B"/>
        <input data-repeater-delete type="button" value="Delete"/>
      </div>
      <div data-repeater-item>
        <input type="radio" name="group-a[1][radio-input]" value="A"/>
        <input type="radio" name="group-a[1][radio-input]" value="B" checked/>
        <input data-repeater-delete type="button" value="Delete"/>
      </div>
    </div>
```

I don't know why but it's was leading to this issue.

When I changed it by following the sample code logic in the README the issue was gone:

```
    <div data-repeater-list="group-a">
      <div data-repeater-item>
        <input type="radio" name="radio-input" value="A" checked/>
        <input type="radio" name="radio-input" value="B"/>
        <input data-repeater-delete type="button" value="Delete"/>
      </div>
      <div data-repeater-item>
        <input type="radio" name="radio-input" value="A"/>
        <input type="radio" name="radio-input" value="B" checked/>
        <input data-repeater-delete type="button" value="Delete"/>
      </div>
    </div>
```

I didn't realized that the jquery.repeater set the inputs' name with the right group and index, so there is no need to prefill those data before jquery.repeater, and then the problem is solved.

But I further investigated the jquery.repeater code and found some suspect line of code:

https://github.com/DubFriend/jquery.repeater/blob/1c3ba62b6a6801f0555cd58ba23706a6b65a4c1e/jquery.repeater.js#L904

And [as of jQuery 3, removeAttr does not set the corresponding property to false anymore](https://stackoverflow.com/a/6170016/880719). So I tried to change it to `.prop('checked', false)` and then it also solved the issue, it works even if I decide to prefill the inputs' name with the group and index.
